### PR TITLE
fix: updated header import paths

### PR DESCRIPTION
**Pull request by abhinav-from-contentstack**
- added a fix for header import issue
- updated version to 3.12.2

### CODE REVIEW

**Review by vkaltasv — APPROVED** [review]

**Comment by vkaltasv** [comment]
Please check the failing workflows @abhinav-from-contentstack

**Review by vkalta — CHANGES_REQUESTED** [review]
Please check failing workflows @abhinav-from-contentstack

**Comment by abhinav-from-contentstack** [comment]
`check_branch` workflow can be ignored as this is a hotfix release.
`sca-scan` is failing due to some issue with snyk. I'll connect with SRE team.
@vkalta @vkaltasv

**Review by aravindbuilt — APPROVED** [review]

**Review by vkalta — APPROVED** [review]

**Review by sunil-lakshman — APPROVED** [review]
Approved

**Pull request merged**
